# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c7b3ac2594d0d5707d9e364a3295fbaefe8a382ec07f9322946d3831d5aff6695aee5c0d3886fe2c7758553d500cb9416277cf1dd423f6722002eb2af5a4952

test:
  secret_key_base: d43bba55878fafe415e32c11ac54fba4a1a540e0f803deef464e6990e49658dd930ac5b1dfcdd11758c87a869a9a7eaf093bad3ab0f17c6920edd3ba464e826f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
